//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productOpp.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        public int poduct_id { get; set; }
        public string porduct_name { get; set; }
        public string product_description { get; set; }
        public string product_price { get; set; }
        public Nullable<System.DateTime> product_date { get; set; }
        public string product_photo { get; set; }
    }
}
